<?xml version="1.0" encoding="utf-8"?><Database Name="ManageRestaurant" Class="RestaurantPPLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MINHTOAN\SQLEXPRESS;Initial Catalog=ManageRestaurant;Persist Security Info=True;User ID=sa" SettingsObjectName="DTO_PPL.Properties.Settings" SettingsPropertyName="ManageRestaurantConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CATEGORY" Member="CATEGORies">
    <Type Name="CATEGORY">
      <Column Name="ID_CATEGORY" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GROUP_CATEGORY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NAME_CATEGORY" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CATEGORY_PRODUCT" Member="PRODUCTs" ThisKey="ID_CATEGORY" OtherKey="ID_CATEGORY" Type="PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.VOUCHER" Member="VOUCHERs">
    <Type Name="VOUCHER">
      <Column Name="ID_VOUCHER" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PROMOTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_END" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TYPE_REDUCTION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE_CUSTOMER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PERCENT_REDUCTION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMOUNT_REDUCTION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY_VOUCHER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VOUCHER_RECEIPT" Member="RECEIPTs" ThisKey="ID_VOUCHER" OtherKey="ID_VOUCHER" Type="RECEIPT" />
      <Association Name="CUSTOMER_TYPE_VOUCHER" Member="CUSTOMER_TYPE" ThisKey="TYPE_CUSTOMER" OtherKey="TYPE_CUSTOMER" Type="CUSTOMER_TYPE" IsForeignKey="true" />
      <Association Name="PROMOTION_VOUCHER" Member="PROMOTION" ThisKey="ID_PROMOTION" OtherKey="ID_PROMOTION" Type="PROMOTION" IsForeignKey="true" />
      <Association Name="STAFF_VOUCHER" Member="STAFF" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER" Member="CUSTOMERs">
    <Type Name="CUSTOMER">
      <Column Name="ID_CUSTOMER" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_CUSTOMER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SURNAME_CUSTOMER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GENDER_CUSTOMER" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_UPDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PHONE_CUSTOMER" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="MAIL_CUSTOMER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="PASSWORD_CUSTOMER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ADDRESS_CUSTOMER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE_OF_BIRTH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="POINT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_CUSTOMER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="CUSTOMER_RECEIPT" Member="RECEIPTs" ThisKey="ID_CUSTOMER" OtherKey="ID_CUSTOMER" Type="RECEIPT" />
      <Association Name="CUSTOMER_TYPE_CUSTOMER" Member="CUSTOMER_TYPE" ThisKey="TYPE_CUSTOMER" OtherKey="TYPE_CUSTOMER" Type="CUSTOMER_TYPE" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CUSTOMER_TYPE" Member="CUSTOMER_TYPEs">
    <Type Name="CUSTOMER_TYPE">
      <Column Name="TYPE_CUSTOMER" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LEVEL_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POINT_MIN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POINT_MAX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POINT_RATE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="CUSTOMER_TYPE_VOUCHER" Member="VOUCHERs" ThisKey="TYPE_CUSTOMER" OtherKey="TYPE_CUSTOMER" Type="VOUCHER" />
      <Association Name="CUSTOMER_TYPE_CUSTOMER" Member="CUSTOMERs" ThisKey="TYPE_CUSTOMER" OtherKey="TYPE_CUSTOMER" Type="CUSTOMER" />
    </Type>
  </Table>
  <Table Name="dbo.DETAIL_IMPORT" Member="DETAIL_IMPORTs">
    <Type Name="DETAIL_IMPORT">
      <Column Name="ID_DETAIL_IOG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_IOG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_INGREDIENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="IMPORT_DETAIL_IMPORT" Member="IMPORT" ThisKey="ID_IOG" OtherKey="ID_IOG" Type="IMPORT" IsForeignKey="true" />
      <Association Name="INGREDIENT_DETAIL_IMPORT" Member="INGREDIENT" ThisKey="ID_INGREDIENT" OtherKey="ID_INGREDIENT" Type="INGREDIENT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETAIL_PRODUCT" Member="DETAIL_PRODUCTs">
    <Type Name="DETAIL_PRODUCT">
      <Column Name="ID_DETAIL" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_PRODUCT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_INGREDIENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WEIGHT_DETAIL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="INGREDIENT_DETAIL_PRODUCT" Member="INGREDIENT" ThisKey="ID_INGREDIENT" OtherKey="ID_INGREDIENT" Type="INGREDIENT" IsForeignKey="true" />
      <Association Name="PRODUCT_DETAIL_PRODUCT" Member="PRODUCT" ThisKey="ID_PRODUCT" OtherKey="ID_PRODUCT" Type="PRODUCT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DETAIL_RECEIPT" Member="DETAIL_RECEIPTs">
    <Type Name="DETAIL_RECEIPT">
      <Column Name="ID_DETAIL_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PRODUCT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PRODUCT_DETAIL_RECEIPT" Member="PRODUCT" ThisKey="ID_PRODUCT" OtherKey="ID_PRODUCT" Type="PRODUCT" IsForeignKey="true" />
      <Association Name="RECEIPT_DETAIL_RECEIPT" Member="RECEIPT" ThisKey="ID_RECEIPT" OtherKey="ID_RECEIPT" Type="RECEIPT" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GROUP_USER" Member="GROUP_USERs">
    <Type Name="GROUP_USER">
      <Column Name="ID_GROUP" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ROLE_USER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="GROUP_USER_STAFF" Member="STAFFs" ThisKey="ID_GROUP" OtherKey="ID_GROUP" Type="STAFF" />
    </Type>
  </Table>
  <Table Name="dbo.IMAGE_NEWS" Member="IMAGE_NEWs">
    <Type Name="IMAGE_NEW">
      <Column Name="ID_IMAGE" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_NEWS" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PATH_IMAGE" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="NEW_IMAGE_NEW" Member="NEW" ThisKey="ID_NEWS" OtherKey="ID_NEWS" Type="NEW" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMPORT" Member="IMPORTs">
    <Type Name="IMPORT">
      <Column Name="ID_IOG" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SUPPLIER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_IOG" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DATE_DELIVERY" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TOTAL_PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NOTE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATE_IMPORT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="IMPORT_DETAIL_IMPORT" Member="DETAIL_IMPORTs" ThisKey="ID_IOG" OtherKey="ID_IOG" Type="DETAIL_IMPORT" />
      <Association Name="STAFF_IMPORT" Member="STAFF" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="STAFF" IsForeignKey="true" />
      <Association Name="SUPPLIER_IMPORT" Member="SUPPLIER" ThisKey="ID_SUPPLIER" OtherKey="ID_SUPPLIER" Type="SUPPLIER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.INGREDIENT" Member="INGREDIENTs">
    <Type Name="INGREDIENT">
      <Column Name="ID_INGREDIENT" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SUPPLIER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NAME_INGREDIENT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="INVENTORY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="INGREDIENT_DETAIL_IMPORT" Member="DETAIL_IMPORTs" ThisKey="ID_INGREDIENT" OtherKey="ID_INGREDIENT" Type="DETAIL_IMPORT" />
      <Association Name="INGREDIENT_DETAIL_PRODUCT" Member="DETAIL_PRODUCTs" ThisKey="ID_INGREDIENT" OtherKey="ID_INGREDIENT" Type="DETAIL_PRODUCT" />
    </Type>
  </Table>
  <Table Name="dbo.METHOD_PAY" Member="METHOD_PAYs">
    <Type Name="METHOD_PAY">
      <Column Name="ID_METHOD" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TYPE_METHOD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_METHOD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="METHOD_PAY_RECEIPT" Member="RECEIPTs" ThisKey="ID_METHOD" OtherKey="ID_METHOD" Type="RECEIPT" />
      <Association Name="STAFF_METHOD_PAY" Member="STAFF" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NEWS" Member="NEWs">
    <Type Name="NEW">
      <Column Name="ID_NEWS" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_PROMOTION" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TITLE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONTENT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DATE_VISIBLE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_HIDDEN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NEW_IMAGE_NEW" Member="IMAGE_NEWs" ThisKey="ID_NEWS" OtherKey="ID_NEWS" Type="IMAGE_NEW" />
      <Association Name="PROMOTION_NEW" Member="PROMOTION" ThisKey="ID_PROMOTION" OtherKey="ID_PROMOTION" Type="PROMOTION" IsForeignKey="true" />
      <Association Name="STAFF_NEW" Member="STAFF" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PRODUCT" Member="PRODUCTs">
    <Type Name="PRODUCT">
      <Column Name="ID_PRODUCT" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_CATEGORY" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_PRODUCT_EN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_PRODUCT_VN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE_PRODUCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IMAGE_PRODUCT" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PRODUCT_DETAIL_PRODUCT" Member="DETAIL_PRODUCTs" ThisKey="ID_PRODUCT" OtherKey="ID_PRODUCT" Type="DETAIL_PRODUCT" />
      <Association Name="PRODUCT_DETAIL_RECEIPT" Member="DETAIL_RECEIPTs" ThisKey="ID_PRODUCT" OtherKey="ID_PRODUCT" Type="DETAIL_RECEIPT" />
      <Association Name="CATEGORY_PRODUCT" Member="CATEGORY" ThisKey="ID_CATEGORY" OtherKey="ID_CATEGORY" Type="CATEGORY" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PROMOTION" Member="PROMOTIONs">
    <Type Name="PROMOTION">
      <Column Name="ID_PROMOTION" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_PROMOTION" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_START" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DATE_END" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PROMOTION_VOUCHER" Member="VOUCHERs" ThisKey="ID_PROMOTION" OtherKey="ID_PROMOTION" Type="VOUCHER" />
      <Association Name="PROMOTION_NEW" Member="NEWs" ThisKey="ID_PROMOTION" OtherKey="ID_PROMOTION" Type="NEW" />
      <Association Name="STAFF_PROMOTION" Member="STAFF" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="STAFF" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT" Member="RECEIPTs">
    <Type Name="RECEIPT">
      <Column Name="ID_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_VOUCHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_CUSTOMER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_METHOD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TOTAL_PRODUCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POINT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATE_RECEIPT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_RECEIPT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="RECEIPT_DETAIL_RECEIPT" Member="DETAIL_RECEIPTs" ThisKey="ID_RECEIPT" OtherKey="ID_RECEIPT" Type="DETAIL_RECEIPT" />
      <Association Name="CUSTOMER_RECEIPT" Member="CUSTOMER" ThisKey="ID_CUSTOMER" OtherKey="ID_CUSTOMER" Type="CUSTOMER" IsForeignKey="true" />
      <Association Name="METHOD_PAY_RECEIPT" Member="METHOD_PAY" ThisKey="ID_METHOD" OtherKey="ID_METHOD" Type="METHOD_PAY" IsForeignKey="true" />
      <Association Name="VOUCHER_RECEIPT" Member="VOUCHER" ThisKey="ID_VOUCHER" OtherKey="ID_VOUCHER" Type="VOUCHER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.STAFF" Member="STAFFs">
    <Type Name="STAFF">
      <Column Name="USERNAME_STAFF" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PASSWORD_STAFF" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_GROUP" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SURNAME_STAFF" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="NAME_STAFF" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GENDER_STAFF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DATE_OF_BIRTH" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ADDRESS_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NUMBER_PHONE" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="STAFF_VOUCHER" Member="VOUCHERs" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="VOUCHER" />
      <Association Name="STAFF_IMPORT" Member="IMPORTs" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="IMPORT" />
      <Association Name="STAFF_METHOD_PAY" Member="METHOD_PAYs" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="METHOD_PAY" />
      <Association Name="STAFF_NEW" Member="NEWs" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="NEW" />
      <Association Name="STAFF_PROMOTION" Member="PROMOTIONs" ThisKey="USERNAME_STAFF" OtherKey="USERNAME_STAFF" Type="PROMOTION" />
      <Association Name="GROUP_USER_STAFF" Member="GROUP_USER" ThisKey="ID_GROUP" OtherKey="ID_GROUP" Type="GROUP_USER" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SUPPLIER" Member="SUPPLIERs">
    <Type Name="SUPPLIER">
      <Column Name="ID_SUPPLIER" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NAME_SUPPLIER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PHONE_SUPPLIER" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="ADDRESS_SUPPLIER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SUPPLIER_IMPORT" Member="IMPORTs" ThisKey="ID_SUPPLIER" OtherKey="ID_SUPPLIER" Type="IMPORT" />
    </Type>
  </Table>
  <Table Name="dbo.DETAILRECEIPT_JOIN" Member="DETAILRECEIPT_JOINs">
    <Type Name="DETAILRECEIPT_JOIN">
      <Column Name="ID_DETAIL_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PRODUCT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME_PRODUCT_VN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_PRODUCT_EN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RECIPE_JOIN" Member="RECIPE_JOINs">
    <Type Name="RECIPE_JOIN">
      <Column Name="ID_DETAIL" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_PRODUCT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_INGREDIENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="WEIGHT_DETAIL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FLAG_DEL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME_PRODUCT_EN" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NAME_INGREDIENT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.IOGDETAIL_JOIN" Member="IOGDETAIL_JOINs">
    <Type Name="IOGDETAIL_JOIN">
      <Column Name="ID_DETAIL_IOG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_IOG" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_INGREDIENT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QUANTITY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NAME_INGREDIENT" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.RECEIPT_FULL" Member="RECEIPT_FULLs">
    <Type Name="RECEIPT_FULL">
      <Column Name="ID_RECEIPT" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ID_VOUCHER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_CUSTOMER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ID_METHOD" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DATE_CREATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="TOTAL_PRODUCT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TOTAL_PRICE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="POINT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATE_RECEIPT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_RECEIPT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PERCENT_REDUCTION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AMOUNT_REDUCTION" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADDRESS_CUSTOMER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MAIL_CUSTOMER" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="NAME_CUSTOMER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SURNAME_CUSTOMER" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PHONE_CUSTOMER" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="NAME_METHOD" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TYPE_METHOD" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>